import { brand } from '../packages/shared/tokens/brand.ts';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../packages/shared/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: 'rgb(var(--brand) / <alpha-value>)',
          accent:  brand.accent,
          dark:    brand.dark,
          cream:   brand.cream,
          border:  brand.border,
          light:   'var(--brand-light)',
          subtle:  'var(--brand-subtle)',
        },
        ink:     'rgb(var(--ink) / <alpha-value>)',
        canvas:  'rgb(var(--canvas) / <alpha-value>)',
        mist:    'rgb(var(--mist) / <alpha-value>)',
        border:  'rgb(var(--border) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        error:   'var(--error)',
        info:    'var(--info)',
      },
      borderRadius: {
        sharp: 'var(--r-sharp)',
        sm:    'var(--r-sm)',
        md:    'var(--r-md)',
        lg:    'var(--r-lg)',
        xl:    'var(--r-xl)',
        '2xl': 'var(--r-2xl)',
        pill:  'var(--r-pill)',
      },
      boxShadow: {
        0: 'var(--sh-0)',
        1: 'var(--sh-1)',
        2: 'var(--sh-2)',
        3: 'var(--sh-3)',
        4: 'var(--sh-4)',
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs:    ['12px', { lineHeight: '16px' }],
        sm:    ['13px', { lineHeight: '18px' }],
        base:  ['14px', { lineHeight: '20px' }],
        md:    ['15px', { lineHeight: '22px' }],
        lg:    ['16px', { lineHeight: '24px' }],
        xl:    ['18px', { lineHeight: '26px' }],
        '2xl': ['20px', { lineHeight: '28px' }],
        '3xl': ['24px', { lineHeight: '32px' }],
        '4xl': ['28px', { lineHeight: '36px' }],
        '5xl': ['36px', { lineHeight: '44px' }],
      },
      transitionDuration: {
        fast:   '150ms',
        normal: '250ms',
        slow:   '400ms',
      },
      zIndex: {
        base:     '0',
        raised:   '10',
        dropdown: '100',
        sticky:   '200',
        overlay:  '300',
        modal:    '400',
        drawer:   '500',
        toast:    '600',
        tooltip:  '700',
      },
      animation: {
        'fade-in':     'fade-in 250ms cubic-bezier(.16,1,.3,1)',
        'slide-up':    'slide-up 250ms cubic-bezier(.16,1,.3,1)',
        'slide-right': 'slide-right 250ms cubic-bezier(.16,1,.3,1)',
        'slide-left':  'slide-left 250ms cubic-bezier(.16,1,.3,1)',
        'scale-in':    'scale-in 150ms cubic-bezier(.34,1.56,.64,1)',
        'drawer-in':   'drawer-in 400ms cubic-bezier(.16,1,.3,1)',
        'sheet-in':    'sheet-in 250ms cubic-bezier(.16,1,.3,1)',
        'modal-in':    'modal-in 250ms cubic-bezier(.34,1.56,.64,1)',
        'toast-in':    'toast-in 150ms cubic-bezier(.16,1,.3,1)',
        'count-up':    'count-up 150ms cubic-bezier(.16,1,.3,1)',
        'ping-once':   'ping-once 600ms cubic-bezier(.16,1,.3,1) forwards',
      },
    },
  },
  plugins: [],
};
